proxy-providers:
  #æœºåœºåå­—ï¼š
  Maker:
    #è®¢é˜…é“¾æ¥ï¼š
    url: 
    #é“¾æ¥æ›´æ–°é—´éš”æ—¶é•¿ï¼šå•ä½ç§’
    interval: 86400
  Amy:
    url: 
    interval: 86400
#ä»£ç†ç­–ç•¥ç»„
proxy-groups:
  - name: ğŸ± PROXY
    proxies:
      - HK é¦™æ¸¯
      - TW å°æ¹¾
      - SG æ–°åŠ å¡
      - US ç¾å›½
      - DIRECT
    type: select
  - name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
    proxies:
    type: select
    use:
      - Amy
      - Maker
  - name: ğŸ“² Telegram
    proxies:
      - ğŸ± PROXY
      - HK é¦™æ¸¯
      - TW å°æ¹¾
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸ’¬ OpenAi
    proxies:
      - US ç¾å›½
      - TW å°æ¹¾
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸ“¹ YouTube
    proxies:
      - ğŸ± PROXY
      - HK é¦™æ¸¯
      - TW å°æ¹¾
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸ¥ Netflix
    proxies:
      - HK é¦™æ¸¯
      - TW å°æ¹¾
      - SG æ–°åŠ å¡
      - US ç¾å›½
    type: select
  - name: ğŸ¥ DisneyPlus
    proxies:
      - DIRECT
      - HK é¦™æ¸¯
      - TW å°æ¹¾
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸ¥ TikTok
    proxies:
      - JP æ—¥æœ¬
      - TW å°æ¹¾
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸ“º å·´å“ˆå§†ç‰¹
    proxies:
      - TW å°æ¹¾
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸ“º å“”å“©å“”å“©
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - HK é¦™æ¸¯
      - TW å°æ¹¾
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸŒ å›½å¤–åª’ä½“
    proxies:
      - ğŸ± PROXY
      - TW å°æ¹¾
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸŒ å›½å†…åª’ä½“
    proxies:
      - DIRECT
      - TW å°æ¹¾
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸ“¢ è°·æ­ŒFCM
    proxies:
      - DIRECT
      - TW å°æ¹¾
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
    type: select
  - name: â“‚ï¸ å¾®è½¯Bing
    proxies:
      - DIRECT
      - TW å°æ¹¾
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
    type: select
  - name: â“‚ï¸ å¾®è½¯äº‘ç›˜
    proxies:
      - DIRECT
      - TW å°æ¹¾
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
    type: select
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    proxies:
      - DIRECT
      - TW å°æ¹¾
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸ Apple
    proxies:
      - DIRECT
      - TW å°æ¹¾
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸ® æ¸¸æˆå¹³å°
    proxies:
      - ğŸ± PROXY
      - TW å°æ¹¾
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸ¯ å…¨çƒç›´è¿
    proxies:
      - DIRECT
      - ğŸ± PROXY
      - TW å°æ¹¾
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
    type: select
  - name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
    proxies:
      - DIRECT
      - DIRECT
    type: select
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    proxies:
      - ğŸ± PROXY
      - TW å°æ¹¾
      - HK é¦™æ¸¯
      - SG æ–°åŠ å¡
    type: select
  # åŸºäºåœ°åŒºåˆ†ç»„
  - name: HK é¦™æ¸¯
    filter: "æ¾³é—¨|ğŸ‡²ğŸ‡´|æ¸¯|ğŸ‡­ğŸ‡°|HK|(?i)Hong"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Hong_Kong.png
    interval: 120
    lazy: true
    tolerance: 50
    type: fallback
    include-all: true
    use:
      - Amy
      - Maker
  - name: TW å°æ¹¾
    filter: "å°|ğŸ‡¹ğŸ‡¼|æ¹¾|TW|(?i)Taiwan"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Taiwan.png
    interval: 120
    lazy: true
    tolerance: 50
    type: fallback
    include-all: true
    use:
      - Amy
      - Maker
  - name: SG æ–°åŠ å¡
    filter: "æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Singapore.png
    interval: 120
    lazy: true
    tolerance: 50
    type: fallback
    include-all: true
    use:
      - Amy
      - Maker
  - name: JP æ—¥æœ¬
    filter: "æ—¥|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|JP|(?i)Japan"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Japan.png
    interval: 120
    lazy: true
    tolerance: 50
    type: fallback
    include-all: true
    use:
      - Amy
      - Maker
  - name: US ç¾å›½
    filter: "ç¾|ğŸ‡ºğŸ‡²|US|(?i)States|America"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/United_States.png
    interval: 120
    lazy: true
    tolerance: 50
    type: fallback
    include-all: true
    use:
      - Amy
      - Maker
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
dns:
  default-nameserver:
    - 223.6.6.6
    - 119.29.29.29
    - system
  nameserver:
    - 223.6.6.6
    - 119.29.29.29
log-level: warning
mode: rule
rule-providers:
  directgb:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/SICKCAT2/Surge/master/rule/directgb.yaml
    format: yaml
  LocalAreaNetwork:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    format: yaml
  UnBan:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
    format: yaml
  BanAD:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    format: yaml
  BanProgramAD:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
    format: yaml
  GoogleFCM:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
    format: yaml
  GoogleCN:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
    format: yaml
  SteamCN:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
    format: yaml
  â“‚ï¸ å¾®è½¯Bing:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
    format: yaml
  Bing:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
    format: yaml
  OneDrive:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
    format: yaml
  Microsoft:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
    format: yaml
  TikTok:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR//master/Clash/Ruleset/TikTok.list
    format: yaml
  DisneyPlus:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DisneyPlus.list
    format: yaml
  Apple:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
    format: yaml
  Telegram:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    format: yaml
  OpenAi:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
    format: yaml
  Epic:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
    format: yaml
  Origin:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
    format: yaml
  Sony:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
    format: yaml
  Steam:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
    format: yaml
  Nintendo:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
    format: yaml
  YouTube:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
    format: yaml
  Netflix:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
    format: yaml
  Bahamut:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
    format: yaml
  BilibiliHMT:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
    format: yaml
  Bilibili:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
    format: yaml
  ChinaMedia:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
    format: yaml
  ProxyMedia:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
    format: yaml
  ProxyGFWlist:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
    format: yaml
  ChinaDomain:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    format: yaml
  ChinaCompanyIp:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    format: yaml
  Download:
    behavior: "classical"
    interval: 7200
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
    format: yaml
rules:
  - RULE-SET,directgb,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,LocalAreaNetwork,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,UnBan,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,BanAD,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,BanProgramAD,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,GoogleFCM,ğŸ“¢ è°·æ­ŒFCM
  - RULE-SET,GoogleCN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,SteamCN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Bing,â“‚ï¸ å¾®è½¯Bing
  - RULE-SET,OneDrive,â“‚ï¸ å¾®è½¯äº‘ç›˜
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,TikTok,ğŸ¥ TikTok
  - RULE-SET,DisneyPlus,ğŸ¥ DisneyPlus
  - RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Telegram,ğŸ“² Telegram
  - RULE-SET,OpenAi,ğŸ’¬ OpenAi
  - RULE-SET,Epic,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Origin,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Sony,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Steam,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Nintendo,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,YouTube,ğŸ“¹ YouTube
  - RULE-SET,Netflix,ğŸ¥ Netflix
  - RULE-SET,Bahamut,ğŸ“º å·´å“ˆå§†ç‰¹
  - RULE-SET,BilibiliHMT,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,Bilibili,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,ChinaMedia,ğŸŒ å›½å†…åª’ä½“
  - RULE-SET,ProxyMedia,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,ProxyGFWlist,ğŸ± PROXY
  - RULE-SET,ChinaDomain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ChinaCompanyIp,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Download,ğŸ¯ å…¨çƒç›´è¿
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
